### ISSUE TITLE
Lean-chat++

### ISSUE THREAD

**Issue by ayush1801** [siddhartha-gadgil/LeanAide#12]
1. Caching of the input prompts in python code/tweaking the `lean3` code to save the input prompts
2. Support chat interface like `lean-chat`
3. Adding key-word based prompts
4. Reverse the prompts in order to keep the most similar example prompt closer to the main prompt.
5. Developing a trusted server for the `HTTP` requests - MS Azure, Google cloud etc.

**Comment by siddhartha-gadgil** [comment]
@0art0 @ayush1801 if everything is done (except the server, which will be done anyway) please close this issue.
