### ISSUE TITLE
Clean up, abstract configuration

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/LeanAide#19]
Currently the many choices involved in translation are scattered across arguments to many functions and are effectively chosen as default arguments. These should be gathered into a structure and passed as an argument, perhaps with a present configuration stored as an `IO.Ref`

A (partial) list of the choices made is the following:

* number of sentences based on similarity
* file from which similarity parameters are taken (e.g. `safe-prompts`).
* field that we look up in the file for similarity.
* function building the prompt statment from the json chosen.
* number based on keywords
* auxiliary keyword parameter choices
* function for string pasted as code, or choices for this (eg `example` vs `theorem`)

In the longer run the cleanup will help in allowing the user to configure. In the shorter run it will make experimenting with including definitions, asking for theorem names, using `mathlib4` etc easy to try out.

**Comment by siddhartha-gadgil** [comment]
In the above, we should allow different sources for prompts, including from files and from keywords, and mixing strategies (including append and interleave).

**Comment by 0art0** [comment]
Another abstraction I found useful in the `lean3` implementation is the [`declaration_with_docstring` structure](https://github.com/0art0/lean3-statement-translation-tool/blob/5bf00c4f3d7ddcae938e4d78349395061b866aab/src/declaration_with_docstring.lean#L4) (which is similar to the [`TheoremAndTactic` structure](https://github.com/siddhartha-gadgil/LeanAide/blob/9719540bc24b7f32966059bcc5cd1128151cd9b3/LeanCodePrompts/FirstTacticData.lean#L80)).

**Comment by siddhartha-gadgil** [comment]
> Another abstraction I found useful in the `lean3` implementation is the [`declaration_with_docstring` structure](https://github.com/0art0/lean3-statement-translation-tool/blob/5bf00c4f3d7ddcae938e4d78349395061b866aab/src/declaration_with_docstring.lean#L4) (which is similar to the [`TheoremAndTactic` structure](https://github.com/siddhartha-gadgil/LeanAide/blob/9719540bc24b7f32966059bcc5cd1128151cd9b3/LeanCodePrompts/FirstTacticData.lean#L80)).

Yes, we can have such a structure and have functions that map to it for the different sources of statements (type only, with name etc).

**Comment by 0art0** [comment]
Rather than using my own custom structure for `declaration_with_docstring`, I realised that it may be cleaner for me to just extend [`Lean.Declaration`](https://github.com/leanprover/lean4/blob/30d625697e13bb23b6ad02aa49d16fe55fbe4bb7/src/Lean/Declaration.lean#L154).

**Comment by 0art0** [comment]
I have created some possible `structure`s for holding the prompt building and querying parameters [here](https://github.com/siddhartha-gadgil/LeanAide/blob/re-structure/LeanCodePrompts/Query.lean).

**Comment by siddhartha-gadgil** [comment]
Looks good. You may need fields to specify the file queried (safe-prompts
vs prompts for example) and what is extracted from the response (type vs
statement for example). The latter may be a separate structure though
(relevant to the prompt construction but not the query).

**Comment by 0art0** [comment]
I have written the code for translation with easy configuration. The configuration files are in [this folder](https://github.com/siddhartha-gadgil/LeanAide/tree/re-structure/StatementAutoformalisation/Config). An example of loading and using a configuration is [here](https://github.com/siddhartha-gadgil/LeanAide/blob/re-structure/StatementAutoformalisation/Experiment.lean).

There are structures for each set of parameters, and also a structure for `Declaration`s (`WithDocstring`s). The code is set up so that both informalisation and direct formalisation can be achieved by adjusting the parameters that determine how a `DeclarationWithDocstring` is displayed in the prompt.
