### ISSUE TITLE
Better Equivalence proving

### ISSUE THREAD

**Issue by siddhartha-gadgil** [siddhartha-gadgil/LeanAide#3]
Proving equivalence of statements can be used for

* grouping completions to "vote" for the best.
* checking correctness of answers.

Unfortunately the current automatic proving is too weak to be effective for the first application, and not even close to good enough for the second.

**Comment by navingoyal** [comment]
What are the existing Lean/mathlib tactics that do some equivalence checking? What are their known limitations?

**Comment by siddhartha-gadgil** [comment]
We can combine tactics to make one. Currently we use an ad hoc basic one, which

- uses `apply Iff.intro` to get the two goals as implication.
- for each direction, use `intro h` to get a hypothesis.
- then try a bunch of stuff based on known examples.

It is the third part one wants to replace (or possibly all three) by a combination tactic. The best one around is called `aesop`, which can be configured to use specific theorems and in specific ways (i.e., for rewrites, applications etc) and also built in tactics. There is no fundamental limitation (other than the Godel, Turing etc), but this is the process of automating proof search (in a rule-based way).

**Comment by navingoyal** [comment]
The kind of equivalence problems we are up against here are likely to have some special characteristics as they are the results of autoformalization using Codex. As a starting point, it would be useful to have some test examples. One (imperfect) way to do this might be to autoformalize mathlib docstrings. Now those that get correctly autoformalized (as revealed by manual inspection) but are not identical to the formalization in mathlib give us our dataset. Apart from requiring manual inspection (some of which seems unavoidable at this point), the issue with this is that Codex may have seen the data. This may not be a big problem. Also, if we use docstrings after the Codex training data cutoff data this should be OK. Such a dataset along with information on how the current algorithms fail (or not) at equivalence checking on this dataset will likely be very useful.

**Comment by siddhartha-gadgil** [comment]
As we collect examples, we can build a tactic (from others) which can handle most (if not all) of them.

**Comment by siddhartha-gadgil** [comment]
There is now a file with target examples : `LeanCodePrompts/EquivalenceProofExercises.lean`. More on Zulip.

**Comment by siddhartha-gadgil** [comment]
We now have comparison with aesop as well as aesop with "power tactics" as options. Should reopen if there is a specific enhancement we need.
