### ISSUE TITLE
about the prompts_subprocesses.py file

### ISSUE THREAD

**Issue by sushrutjog** [siddhartha-gadgil/LeanAide#43]
there seems to be some issue with line 7 of the file `prompts_subprocesses.py` - `from openai_query import chat`. the function `chat` does not exist in said file. i suspect because of exactly this i am getting this message while trying to run LeanAide:
 
<img width="160" alt="image" src="https://github.com/user-attachments/assets/57bc69ab-0481-4649-bb1b-09d97c5eeeab">

**Comment by siddhartha-gadgil** [comment]
A lot of the python code is not maintained. Only `gemini_structured` and its dependencies have been used recently.

**Comment by siddhartha-gadgil** [comment]
As I see from git, this was created by Ayush Agrawal, a collaborator in an earlier phase, for his use. The current way to use models is `scripts/queries.py` (this may also have issues but is worth maintaining).

**Comment by siddhartha-gadgil** [comment]
As I see from git, this was created by Ayush Agrawal, a collaborator in an earlier phase, for his use. The current way to use models is scripts/queries.py (this may also have issues but is worth maintaining).
